apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::172149903700:user/github-ci
      username: github-ci
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapUsers":"- userarn: arn:aws:iam::172149903700:user/github-ci\n  username: github-ci\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-07-24T20:30:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "70197"
  uid: a25fc5dc-33b9-49a8-ad1e-2ffe9a401f3d
