apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::172149903700:role/AWSEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::172149903700:role/github-ci-deploy
      username: github-ci-deploy
      groups:
        - system:masters
  mapUsers: |
    - userarn: AIDASQFHPCFKAEW3BMCHX
      username: github-ci
      groups:
        - system:masters
    - userarn: arn:aws:iam::172149903700:root
      username: aws-root
      groups:
        - system:masters
